version: '3.2'

services:
    php:
        build: docker/php
        volumes:
            - ./labyrinth:/app
        working_dir: /app
        depends_on:
            - postgres
            - api

    api:
        image: node:10-alpine
        user: '${UID}:${GID}'
        volumes:
            - './labyrinth-api:/app'
        command: './node_modules/.bin/nodemon server/index.js'
        environment:
            - HOME=/app/var/cache
        working_dir: /app

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=labyrinth
            - POSTGRES_PASSWORD=labyrinth
            - POSTGRES_DB=labyrinth
        expose:
            - '5432'
        volumes:
            - labyrinth-pg-data:/var/lib/postgresql/data
volumes:
    labyrinth-pg-data: {}
