version: '3.2'

services:
    php:
        command: 'php bin/console server:run 0.0.0.0:8000'
        ports:
            - 8000:8000
        env_file: ./labyrinth/.env

    api:
        ports:
            - '3000:3000'
