version: '3.2'

services:
    php:
        build: docker/php
        command: 'php bin/console server:run 0.0.0.0:8000'
        ports:
            - 8000:8000
        volumes:
            - ./labyrinth:/app
        working_dir: /app
        depends_on:
            - postgres

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=labyrinth
            - POSTGRES_PASSWORD=labyrinth
            - POSTGRES_DB=labyrinth
        ports:
            - '5433:5432'
        expose:
            - '5432'
        volumes:
            - labyrinth-pg-data:/var/lib/postgresql/data
volumes:
    labyrinth-pg-data: {}
